// <auto-generated />
using AppTroveV1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppTroveV1.Migrations
{
    [DbContext(typeof(App2Context))]
    [Migration("20221024222310_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppTroveV1.Models.App", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppId");

                    b.ToTable("Apps");

                    b.HasData(
                        new
                        {
                            AppId = 1,
                            Name = "Angry Birds",
                            Price = 0.0,
                            Publisher = "Rovio Entertainment"
                        },
                        new
                        {
                            AppId = 2,
                            Name = "Summoner's War",
                            Price = 0.0,
                            Publisher = "Com2Us"
                        },
                        new
                        {
                            AppId = 3,
                            Name = "Pokemon Go",
                            Price = 0.0,
                            Publisher = "Niantic"
                        },
                        new
                        {
                            AppId = 4,
                            Name = "Genshin Impact",
                            Price = 0.0,
                            Publisher = "Mihoyo"
                        },
                        new
                        {
                            AppId = 5,
                            Name = "Paprika Recipe Manager 3",
                            Price = 4.9900000000000002,
                            Publisher = "Hindsight Labs LLC"
                        },
                        new
                        {
                            AppId = 6,
                            Name = "RadarScope",
                            Price = 9.9900000000000002,
                            Publisher = "Base Velocity, LLC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
